### ISSUE TITLE
The Bitpay payment plugin was called to process an IPN message but could not retrieve the order details for order_id ...

### ISSUE THREAD

**Issue by nagypal0121** [bitpay/woocommerce-plugin#87]
I am receiving the following error, and the order statuses are not updating. Could anyone point out what could be the issue?

2018-07-22T10:13:00+00:00 CRITICAL Uncaught Exception: The Bitpay payment plugin was called to process an IPN message but could not retrieve the order details for order_id KA180722-000530. Cannot continue! in /home/***/public_html/***/wp-content/plugins/bitpay-for-woocommerce/class-wc-gateway-bitpay.php:868
Stack trace:
#0 /home/***/public_html/***/wp-includes/class-wp-hook.php(286): WC_Gateway_Bitpay->ipn_callback('')
#1 /home/***/public_html/***/wp-includes/class-wp-hook.php(310): WP_Hook->apply_filters('', Array)
#2 /home/***/public_html/***/wp-includes/plugin.php(453): WP_Hook->do_action(Array)
#3 /home/***/public_html/***/wp-content/plugins/woocommerce/includes/class-wc-api.php(97): do_action('woocommerce_api...')
#4 /home/***/public_html/***/wp-includes/class-wp-hook.php(286): WC_API->handle_api_requests(Object(WP))
#5 /home/***/public_html/***/wp-includes/class-wp-hook.php(310): WP_Hook->apply_filters(NULL, Array)
#6 /home/***/p

PHP 7 Woocommerce 3.4.3 Wordpress 4.9.7

**Comment by nagypal0121** [comment]
I found this article about the custom order numbers, I am using the WooCommerce Sequential Order Numbers Pro plugin.

https://support.bitpay.com/hc/en-us/articles/203032559-How-do-I-fix-mismatched-order-invoice-numbers-on-WooCommerce-when-using-Sequential-Order-Number-plugin-

I made the changes but i am still getting the same error.

**Comment by pieterpoorthuis** [comment]
The BitPay plugin should natively support alternative order numbers

**Comment by pieterpoorthuis** [comment]
Issue resides here: https://github.com/bitpay/woocommerce-plugin/blob/master/src/class-wc-gateway-bitpay.php#L860
